version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changed!
    ports:
      - "8000:8000"
      - "5555:5555"
      - "8088:8088"
      - "8089:8089"
      - "15000:15000"
      - "10667:10667"
      - "10668:10668/udp"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'https://localhost:8000' ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - log_volume:/logs

  monitoring-service:
    image: monitoring-service
    container_name: monitoring-service
    environment:
      - LOGGING_FILE_NAME=/logs/monitoring-service.log
    ports:
      - "8084:8084"
    volumes:
      - log_volume:/logs

  shop-cart-service:
    image: shop-cart-service
    container_name: shop-cart-service
    environment:
      - LOGGING_FILE_NAME=/logs/shop-cart-service.log
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - monitoring-service
    volumes:
      - log_volume:/logs

  shop-validator:
    image: shop-catalog-service
    container_name: shop-catalog-service
    environment:
      - LOGGING_FILE_NAME=/logs/shop-cart-service.log
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - monitoring-service
    volumes:
      - log_volume:/logs

  shop-report:
    image: shop-report-service
    container_name: shop-report-service
    environment:
      - LOGGING_FILE_NAME=/logs/shop-cart-service.log
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - monitoring-service
    volumes:
      - log_volume:/logs

volumes:
  log_volume: