server:
  port: ${PORT:8080}

kafka:
  bootstrapAddress: kafka:9092

spring:
  boot:
    admin:
      client:
        url:http://monitoring-service:8084
  application:
    name: shop-cart
  datasource:
    url: jdbc:h2:mem:shopcart
    driver-class-name: org.h2.Driver
    username: shopcart
    password: shopcart
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  logstash:
    server: logstash
    port: 5000
  zipkin:
    base-url: ${ZIPKIN_URL:http://zipkin:9411}/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
